### ISSUE TITLE
Change signature name: KoblitzSignature2016 -> EcdsaKoblitzSignature2016

### ISSUE THREAD

**Issue by harlantwood** [w3c-ccg/lds-koblitz2016#1]
Based on this discussion: https://github.com/digitalbazaar/jsonld-signatures/pull/10

**Comment by msporny** [comment]
Sounds good to me. Feel free to submit a PR, or I'll change it the next time I'm editing that spec (which probably won't be any time soon).

**Comment by harlantwood** [comment]
Closed with #4.
